### ISSUE TITLE
Unable to locate dependency AspNetWindowsService on install->dnurestore

### ISSUE THREAD

**Issue by Roar1827** [taskmatics/aspnet-windows-service#1]
I have cloned the repository, and successfully built from within visual studio. When building from the command line using "install" I encounter the following error:
![image](https://cloud.githubusercontent.com/assets/4673180/11302009/be32918a-8f68-11e5-9605-c6d1d44d6bbc.png)

**Comment by easyt** [comment]
I get that error as well, but it should not matter. It still runs on my side. Can you verify that you have the rc1 of DNX installed on your machine?

**Comment by Roar1827** [comment]
I have 1.0.0-rc1-final installed. 

![image](https://cloud.githubusercontent.com/assets/4673180/11306364/4b35d09a-8f7f-11e5-897f-c55604db1d30.png)

**Comment by Roar1827** [comment]
Thanks @easyt ! this issue has been resolved.

This error while running install is expected:
![image](https://cloud.githubusercontent.com/assets/4673180/11311702/73bb6762-8f9f-11e5-99fd-e6144f29f63a.png)

It turns out the service would not start due to an issue with my install of ASP.NET 5.  

Details on DNVM and getting the correct version of DNX can be found here: http://docs.asp.net/en/latest/getting-started/installing-on-windows.html
